os: osx
language: swift
git:
  depth: 1
stages:
  - name: test
branches:
  only:
    - ci

jobs:
  include:
    - stage: test
      name: Swift Build (Swift Package Manager)
      osx_image: xcode11.4
      script: swift build

